# server port
#server:
  #port: 8080

# database
#spring:
  #datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/restaurant?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #username: root
    #password: 1234

# mybatis
#mybatis:
  #mapper-locations: classpath:mapper/*.xml
  #config-location: classpath:mybatis-config.xml


server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  sql:
    init:
      mode: always

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
